/// <reference path="typings/express/express.d.ts" />
/// <reference path="typings/express-serve-static-core/express-serve-static-core.d.ts" />
/// <reference path="typings/mime/mime.d.ts" />
/// <reference path="typings/node/node.d.ts" />
/// <reference path="typings/body-parser/body-parser.d.ts" />
/// <reference path="typings/serve-static/serve-static.d.ts" />
/// <reference path="typings/compression/compression.d.ts" />
/// <reference path="typings/method-override/method-override.d.ts" />
/// <reference path="typings/morgan/morgan.d.ts" />
/// <reference path="typings/ejs/ejs.d.ts" />
//# sourceMappingURL=__server_references.js.map